#!/usr/bin/env bash
# scripts/generate-splashes.sh
# Generates per-resolution splash SVGs and exports them as PNGs to the Android res folders.
# Run from anywhere: bash scripts/generate-splashes.sh
#
# Layout logic (all computed from target W×H):
#   font_size  = floor(min(W,H) * 0.22)
#   h_offset   = floor(font_size * 0.57)   -- horizontal gap (X cols visually aligned)
#   v_offset   = floor(font_size * 0.80)   -- vertical gap
#   text_width = floor(font_size * 1.85)   -- approx width of "PXL" at this font-size
#   cap_height = floor(font_size * 0.72)   -- approx cap height
#   group_w    = text_width + h_offset      -- bounding box of both PXLs horiz
#   group_h    = cap_height + v_offset      -- bounding box of both PXLs vert
#   primary_x  = floor((W - group_w) / 2)  -- centres the pair horizontally
#   primary_y  = floor((H - group_h) / 2 + cap_height)  -- centres pair vertically (baseline)
#   echo_x     = primary_x + h_offset
#   echo_y     = primary_y + v_offset
#
# Gradient: identical to logo-9 — #9B59FF → #4A00B8 (at 45%) → #0A0020, 135° diagonal.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR%/*}"
RES="$PROJECT_ROOT/android/app/src/main/res"
SVG_DIR="$PROJECT_ROOT/src/assets/logo/splashes"
mkdir -p "$SVG_DIR"

# Associative array: folder → WxH
declare -A TARGETS=(
  [drawable-port-mdpi]="320x480"
  [drawable-port-hdpi]="480x800"
  [drawable-port-xhdpi]="720x1280"
  [drawable-port-xxhdpi]="960x1600"
  [drawable-port-xxxhdpi]="1280x1920"
  [drawable-land-mdpi]="480x320"
  [drawable-land-hdpi]="800x480"
  [drawable-land-xhdpi]="1280x720"
  [drawable-land-xxhdpi]="1600x960"
  [drawable-land-xxxhdpi]="1920x1280"
)

for folder in "${!TARGETS[@]}"; do
  dim="${TARGETS[$folder]}"
  W="${dim%%x*}"
  H="${dim##*x}"

  # Compute layout values via awk (integer arithmetic)
  read -r fs h_off v_off pw py ex ey <<< "$(awk -v W="$W" -v H="$H" 'BEGIN {
    fs   = int((W < H ? W : H) * 0.22)
    hoff = int(fs * 0.57)
    voff = int(fs * 0.80)
    tw   = int(fs * 1.85)
    ch   = int(fs * 0.72)
    gw   = tw + hoff
    gh   = ch + voff
    px   = int((W - gw) / 2)
    py   = int((H - gh) / 2 + ch)
    ex   = px + hoff
    ey   = py + voff
    if (px < 10) px = 10
    if (py < fs) py = fs
    print fs, hoff, voff, px, py, ex, ey
  }')"

  SVG="$SVG_DIR/splash-${folder}.svg"

  cat > "$SVG" <<SVGEOF
<!-- splash-${folder}.svg  ${W}x${H}
     font-size=${fs}  primary=(${pw},${py})  echo=(${ex},${ey})
     Generated by scripts/generate-splashes.sh — edit values above and re-run to regenerate PNG.
-->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%"   stop-color="#9B59FF"/>
      <stop offset="30%"  stop-color="#8B3FFF"/>
      <stop offset="38%"  stop-color="#6C25E3"/>
      <stop offset="52%"  stop-color="#3A0090"/>
      <stop offset="65%"  stop-color="#1A0040"/>
      <stop offset="100%" stop-color="#0A0020"/>
    </linearGradient>
  </defs>

  <!-- Background -->
  <rect width="${W}" height="${H}" fill="url(#bg)"/>

  <!-- Echo PXL — orange #FFB347 -->
  <text
    x="${ex}" y="${ey}"
    font-family="'Futura', 'Nunito', 'Montserrat', 'Arial Black', sans-serif"
    font-size="${fs}"
    font-weight="900"
    letter-spacing="-2"
    fill="#FFB347"
  >PXL</text>

  <!-- Primary PXL — white -->
  <text
    x="${pw}" y="${py}"
    font-family="'Futura', 'Nunito', 'Montserrat', 'Arial Black', sans-serif"
    font-size="${fs}"
    font-weight="900"
    letter-spacing="-2"
    fill="#FFFFFF"
  >PXL</text>
</svg>
SVGEOF

  echo "wrote $SVG  (${W}x${H}, font=${fs}, primary=(${pw},${py}), echo=(${ex},${ey}))"
done

echo ""
echo "--- Exporting PNGs ---"

for folder in "${!TARGETS[@]}"; do
  dim="${TARGETS[$folder]}"
  W="${dim%%x*}"
  H="${dim##*x}"
  SVG="$SVG_DIR/splash-${folder}.svg"
  OUT="$RES/$folder/splash.png"
  inkscape --export-type=png --export-width="$W" --export-height="$H" "$SVG" -o "$OUT"
  echo "$folder: $(identify -format '%wx%h' "$OUT")"
done

echo ""
echo "Done. Review the SVGs in $SVG_DIR before committing."

# --- Play Store Feature Graphic (1024x500) ---
echo ""
echo "--- Generating Play Store feature graphic (1024x500) ---"

FG_W=1024
FG_H=500
FG_SVG="$PROJECT_ROOT/src/assets/logo/feature-graphic.svg"
FG_PNG="$PROJECT_ROOT/src/assets/logo/feature-graphic.png"

read -r fs h_off v_off pw py ex ey <<< "$(awk -v W="$FG_W" -v H="$FG_H" 'BEGIN {
  fs   = int((W < H ? W : H) * 0.22)
  hoff = int(fs * 0.57)
  voff = int(fs * 0.80)
  tw   = int(fs * 1.85)
  ch   = int(fs * 0.72)
  gw   = tw + hoff
  gh   = ch + voff
  px   = int((W - gw) / 2)
  py   = int((H - gh) / 2 + ch)
  ex   = px + hoff
  ey   = py + voff
  if (px < 10) px = 10
  if (py < fs) py = fs
  print fs, hoff, voff, px, py, ex, ey
}')"

cat > "$FG_SVG" <<SVGEOF
<!-- feature-graphic.svg  ${FG_W}x${FG_H}
     Play Store feature graphic
     font-size=${fs}  primary=(${pw},${py})  echo=(${ex},${ey})
     Generated by scripts/generate-splashes.sh — edit values above and re-run to regenerate PNG.
-->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 ${FG_W} ${FG_H}" width="${FG_W}" height="${FG_H}">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%"   stop-color="#9B59FF"/>
      <stop offset="30%"  stop-color="#8B3FFF"/>
      <stop offset="38%"  stop-color="#6C25E3"/>
      <stop offset="52%"  stop-color="#3A0090"/>
      <stop offset="65%"  stop-color="#1A0040"/>
      <stop offset="100%" stop-color="#0A0020"/>
    </linearGradient>
  </defs>

  <!-- Background -->
  <rect width="${FG_W}" height="${FG_H}" fill="url(#bg)"/>

  <!-- Echo PXL — orange #FFB347 -->
  <text
    x="${ex}" y="${ey}"
    font-family="'Futura', 'Nunito', 'Montserrat', 'Arial Black', sans-serif"
    font-size="${fs}"
    font-weight="900"
    letter-spacing="-2"
    fill="#FFB347"
  >PXL</text>

  <!-- Primary PXL — white -->
  <text
    x="${pw}" y="${py}"
    font-family="'Futura', 'Nunito', 'Montserrat', 'Arial Black', sans-serif"
    font-size="${fs}"
    font-weight="900"
    letter-spacing="-2"
    fill="#FFFFFF"
  >PXL</text>
</svg>
SVGEOF

echo "wrote $FG_SVG  (${FG_W}x${FG_H}, font=${fs}, primary=(${pw},${py}), echo=(${ex},${ey}))"
inkscape --export-type=png --export-width="$FG_W" --export-height="$FG_H" "$FG_SVG" -o "$FG_PNG"
echo "feature-graphic: $(identify -format '%wx%h' "$FG_PNG")"
